blank_issues_enabled: false
contact_links:
- name: '📚 Create an Issue'
  about: Create an issue if something does not work as expected or suggest new functionality/improvements to the product suite.
  url: https://github.com/wso2/micro-integrator/issues/new/choose
- name: Chat on help-micro-integrator Discord Channel
  url: https://discord.com/invite/Xa5VubmThw
  about: "Chat about anything else with the community."
