CREATE TABLE HT_DEPLOYMENT_UNIT (id BIGINT NOT NULL, CHECKSUM VARCHAR(255) NOT NULL, DEPLOYED_ON DATETIME, DEPLOY_DIR VARCHAR(255) NOT NULL, NAME VARCHAR(255) NOT NULL, PACKAGE_NAME VARCHAR(255) NOT NULL, STATUS VARCHAR(255) NOT NULL, TENANT_ID BIGINT NOT NULL, VERSION BIGINT NOT NULL, PRIMARY KEY (id)) ENGINE = innodb;
CREATE TABLE HT_VERSIONS (id BIGINT NOT NULL, TASK_VERSION BIGINT NOT NULL, PRIMARY KEY (id)) ENGINE = innodb;
ALTER TABLE HT_TASK ADD COLUMN PACKAGE_NAME VARCHAR(255) NOT NULL;
ALTER TABLE HT_TASK ADD COLUMN TASK_DEF_NAME VARCHAR(255) NOT NULL;
ALTER TABLE HT_TASK ADD COLUMN TASK_VERSION BIGINT NOT NULL; 



